{
 "title": "Gitea",
 "description": "Gitea metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Issues",
   "type": "gauge",
   "description": "Number of Issues",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gitea_issues" }
   ]
  },
  {
   "title": "Comments",
   "type": "singlestat",
   "description": "gitea_comments Number of Comments",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitea_comments" }
   ]
  },
  {
   "title": "Stars",
   "type": "singlestat",
   "description": "gitea_stars Number of Stars",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitea_stars" }
   ]
  },
  {
   "title": "Actions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitea_actions" }
   ]
  },
  {
   "title": "Releases",
   "type": "singlestat",
   "description": "gitea_releases Number of Releases",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitea_releases" }
   ]
  },
  {
   "title": "Watches",
   "type": "singlestat",
   "description": "gitea_watches Number of Watches",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitea_watches" }
   ]
  },
  {
   "title": "Repositories",
   "type": "singlestat",
   "description": "gitea_repositories",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitea_repositories" }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitea_users" }
   ]
  },
  {
   "title": "Teams",
   "type": "singlestat",
   "description": "gitea_teams Number of Teams",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitea_teams" }
   ]
  },
  {
   "title": "Organizations",
   "type": "singlestat",
   "description": "gitea_organizations Number of Organizations",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitea_organizations" }
   ]
  },
  {
   "title": "HookTasks",
   "type": "graph",
   "description": "gitea_hooktasks Number of HookTasks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitea_hooktasks" }
   ]
  },
  {
   "title": "Accesses",
   "type": "graph",
   "description": "gitea_accesses Number of Accesses",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitea_accesses" }
   ]
  }
 ]
}