{
 "title": "Nextcloud",
 "description": "Export Nextcloud metrics",
 "tags": [
  "cloud",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Auth Errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_auth_errors_total", "legendFormat": "Auth Errors Total" },
    {}
   ]
  },
  {
   "title": "Nextcloud Up ?",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(nextcloud_up)" }
   ]
  },
  {
   "title": "Shares",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nextcloud_shares_federated_total)",
     "legendFormat": "Federated Total"
    },
    { "expr": "sum(nextcloud_shares_total)", "legendFormat": "Total Shares" }
   ]
  },
  {
   "title": "Files Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_files_total", "legendFormat": "Files Total" }
   ]
  },
  {
   "title": "User Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_users_total", "legendFormat": "Users Total" },
    { "expr": "nextcloud_active_users_total", "legendFormat": "Users Active" }
   ]
  },
  {
   "title": "Scrape Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_scrape_errors_total", "legendFormat": "Scrape Errors Total" }
   ]
  }
 ]
}