{
 "title": "OpenLDAP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Object Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Bytes,cn=Statistics,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Object Read",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Read,cn=Waiters,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Object Write",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Write,cn=Waiters,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Operation Add",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Add,cn=Operations,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Operation Delete",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Delete,cn=Operations,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Object Entries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Entries,cn=Statistics,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Connections Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Total,cn=Connections,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Connections Current",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Current,cn=Connections,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Searches",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Search,cn=Operations,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Bind",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Bind,cn=Operations,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Unbind",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Unbind,cn=Operations,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Operation Modify",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Modify,cn=Operations,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Operation Abandon",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Abandon,cn=Operations,cn=Monitor\"}"
    }
   ]
  },
  {
   "title": "Scrape",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "openldap_scrape" }
   ]
  }
 ]
}